### PR TITLE
Support jdk8 classes using lambdas

### PR DESCRIPTION
**Pull request by pedro-stanaka**
This PR is being submitted as means to solve issue #90. A quick summary of what I did in the PR:
1. Upgraded Paranamer library to 2.8
2. Moved target and sorce java version to 1.8 (JDK 8) to use lambdas in tests.
3. Added tests to make sure that classes with lambda expressions will work with fixture-factory.

If I am supposed to do improvements or fix any kind of error let me know.

### CODE REVIEW

**Comment by aparra** [comment]
Hi @pedro-stanaka. Could you explain a little bit more about your idea?

Did you have any problem to use f-f with Java 8 and lambdas expressions? I didn't see any changes in the core. Did you have problems with paranamer:2.5?

cc/ @ahirata

**Comment by pedro-stanaka** [comment]
Hi, @aparra! My idea is only to upgrade the paranamer lib to version 2.8 which solves the problem. 
The only thing I did after that was to add some tests to ensure that f-f is going to be able to resolve constructor parameters using the new version of paranamer. 

For more information check the issue #91 that I reported.

**Comment by aparra** [comment]
Thanks @pedro-stanaka, I got it now. It looks good.

Hey @ahirata / @nykolaslima, could you use this version run some tests? You guys have a bigger test suite. I guess if we don't have problems, we can merge it.

**Comment by pedro-stanaka** [comment]
Thanks guys, I look forward to the publication of a hotfix version in the repositories. :smiley:

**Comment by tbockman-rms** [comment]
Hey guys - I'm currently using lift, which piggybacks off this library. I'm running into the same issue as @pedro-stanaka and I'm wondering what the progress is on this PR. I sure could use it.

Is there any intention to merge this in anytime soon?

**Comment by douglasrodrigo** [comment]
@ahirata  could you take a look?

**Comment by ignacio83** [comment]
Hi guys, this PR will be merging? I am using Lambda in compareTo method and paranamer throws a java.lang.ArrayIndexOutOfBoundsException.

**Comment by pedro-stanaka** [comment]
Hello guys! @ahirata @douglasrodrigo what is stopping this PR from being merged? Can I do something else?

**Pull request merged**
